---
- name: check if MySQL is running with jemalloc
  shell: 'cat /proc/`pidof mysqld`/environ | grep -c "jemalloc"'
  changed_when: false
  ignore_errors: yes
  register: percona_mysql_jemalloc_enabled
  when: percona_mysql_include_tokudb_variables
  tags: percona_mysql_tokudb_prereq

- name: Fail if MySQL is running with jemalloc
  fail: msg='MySQL is not running with jemalloc, TokuDB is dependent on MySQL running with jemalloc'
  when: percona_mysql_include_tokudb_variables and percona_mysql_jemalloc_enabled.stdout|int == 0
  tags: percona_mysql_tokudb_prereq

- name: Check if TokuDB is enabled
  shell: 'mysql -BNe ''show plugins'' | grep ACTIVE | cut -f1 | grep -ci TokuDB'
  changed_when: false
  ignore_errors: yes
  register: percona_mysql_tokudb_enabled
  when: percona_mysql_include_tokudb_variables

- name: Fail if TokuDB is partially installed
  fail: msg='It looks like TokuDB is already partially installed, please investigate and resolve manually'
  when: percona_mysql_include_tokudb_variables and percona_mysql_tokudb_enabled.stdout|int > 0 and percona_mysql_tokudb_enabled.stdout|int < 7
  tags: percona_mysql_tokudb_prereq

- name: Check whether Transparent HugePages are enabled for this session
  shell: 'cat /sys/kernel/mm/transparent_hugepage/defrag | grep -Po "\[\K[^\]]*"'
  changed_when: false
  ignore_errors: yes
  register: percona_mysql_transparent_hugepages_defrag
  when: percona_mysql_include_tokudb_variables
  tags: percona_mysql_tokudb_prereq

- name: Disable Transparent HugePages for this session
  shell: echo never > /sys/kernel/mm/transparent_hugepage/defrag
  when: percona_mysql_include_tokudb_variables and percona_mysql_transparent_hugepages_defrag.stdout == 'always'
  tags: percona_mysql_tokudb_prereq

- name: Install TokuDB if MySQL is already running
  shell: mysql -e {{ item }}
  with_items:
    - '"INSTALL PLUGIN TokuDB SONAME ''ha_tokudb.so'';"'
    - '"INSTALL PLUGIN tokudb_file_map SONAME ''ha_tokudb.so'';"'
    - '"INSTALL PLUGIN tokudb_fractal_tree_info SONAME ''ha_tokudb.so'';"'
    - '"INSTALL PLUGIN tokudb_fractal_tree_block_map SONAME ''ha_tokudb.so'';"'
    - '"INSTALL PLUGIN tokudb_trx SONAME ''ha_tokudb.so'';"'
    - '"INSTALL PLUGIN tokudb_locks SONAME ''ha_tokudb.so'';"'
    - '"INSTALL PLUGIN tokudb_lock_waits SONAME ''ha_tokudb.so'';"'
  when: percona_mysql_include_tokudb_variables and percona_mysql_tokudb_enabled.stdout|int == 0

- name: Check if Audit logging is enabled
  shell: 'mysql -BNe ''show plugins'' | grep ACTIVE | cut -f1 | grep -ci audit_log'
  changed_when: false
  ignore_errors: yes
  register: percona_mysql_auditlog_enabled
  when: percona_mysql_include_auditlog_variables

- name: Install Audit logging if MySQL is already running
  shell: mysql -e {{ item }}
  with_items:
    - '"INSTALL PLUGIN audit_log SONAME ''audit_log.so'';"'
  when: percona_mysql_include_auditlog_variables and percona_mysql_auditlog_enabled.stdout|int == 0